MODEL:
  WEIGHT: "catalog://ImageNetPretrained/DLA34"
INPUT:
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
DATASETS:
  DETECT_CLASSES: ("bicycle", "bus", "car", "construction_vehicle", "motorcycle", "pedestrian", "trailer", "truck")
  MAX_OBJECTS: 128
  TRAIN: ("nusc_train_full",)
  TEST: ("nusc_val_full",)
SOLVER:
  BASE_LR: 1.25e-4
  STEPS: (400000, 500000)
  MAX_ITERATION: 600000
  IMS_PER_BATCH: 32
  CHECKPOINT_PERIOD: 500
TEST:
  TEST_TYPE: "detection_camera"